[package]
name = "license_score"
version = "0.1.0"
authors = ["yuta-natsume <natsume.yuta@classmethod.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"

[dev-dependencies]
rstest = "0.6.4"
